// Explicit reviewed native configuration projection. No credentials or file handles.
export const SETTINGS_KEYS = [
  'mycall',
  'mygrid',
  'opName',
  'opState',
  'catBrokerPtt',
  'band',
  'dialMhz',
  'sideband',
  'phoneMode',
  'rptrShift',
  'ctcssToneHz',
  'q65PeriodS',
  'beaconTxPercent',
  'beaconPowerDbm',
  'beaconRrSlot',
  'beaconRrSlots',
  'fst4PeriodS',
  'msk144PeriodS',
  'jt65Submode',
  'q65Submode',
  'js8Speed',
  'js8RxSpeeds',
  'js8HbIntervalMin',
  'js8CqIntervalMin',
  'js8HbAck',
  'js8Autoreply',
  'js8Relay',
  'js8IdleWatchdogMin',
  'js8Info',
  'js8Status',
  'js8Groups',
  'rptrOffsetOverrideHz',
  'fdActive',
  'fdClass',
  'fdEvent',
  'fdPowerMult',
  'fdBonuses',
  'fdBonusesPlanned',
  'n3fjpHost',
  'n3fjpPort',
  'n3fjpUseEnter',
  'n3fjpReportBand',
  'dxkeeperHost',
  'dxkeeperBasePort',
  'dxkeeperUploads',
  'n1mmAddr',
  'n1mmUpload',
  'fdSection',
  'fdOperator',
  'fdHostEnable',
  'fdHostPort',
  'fdEventName',
  'fdJoinAddr',
  'fdPositionName',
  'fdPositionId',
  'fdScoreboard',
  'fdScoreboardPort',
  'connectWeb',
  'connectWebPort',
  'betaUpdates',
  'beacon',
  'harqEnabled',
  'pttMethod',
  'rigModel',
  'rigModelName',
  'serialPort',
  'pttSerialPort',
  'catRtsState',
  'catDtrState',
  'catRtsKeysPtt',
  'catSerialHandshake',
  'catPttLineState',
  'baud',
  'rigConn',
  'rigAddr',
  'omnirigSlot',
  'icomNativeCat',
  'splitDetectEnabled',
  'yaesuRfScope',
  'icomDataMode',
  'dataModesPlainSsb',
  'sstvHoldDataSubmode',
  'setRigMode',
  'operatingMode',
  'licenseClass',
  'cwKeyer',
  'winkeyerPort',
  'cwKeyPort',
  'cwKeyLine',
  'cwPitchHz',
  'cwWpm',
  'rttyBackend',
  'rttyFskLine',
  'rttyFskPort',
  'rttyBaud',
  'rttyShiftHz',
  'rttyReverse',
  'aiCwEnabled',
  'unassistedMode',
  'rigctldPort',
  'rotatorModel',
  'rotatorPort',
  'rotatorBaud',
  'ampModel',
  'ampPort',
  'ampFollowBand',
  'rotatorHost',
  'rotParkAz',
  'rotParkEl',
  'rotReadyAz',
  'rotReadyEl',
  'rotPostPass',
  'rotTolAzDeg',
  'rotTolElDeg',
  'rotCalAzDeg',
  'rotCalElDeg',
  'rotAllowFlip',
  'satDopplerOff',
  'satVfoMap',
  'satUplinkRadios',
  'satMinShiftHz',
  'satUpdateMs',
  'satPassAlertSoundOff',
  'catBroker',
  'catBrokerPort',
  'flexRadioIp',
  'flexNativePan',
  'flexNativeAudio',
  'radios',
  'activeRadio',
  'radioPegged',
  'simultaneousRadios',
  'routingRules',
  'defaultRadio',
  'wsjtxUdp',
  'wsjtxUdpAddr',
  'writeAllTxt',
  'diagDebugLog',
  'hrdLogging',
  'hrdUdpAddr',
  'companionAddr',
  'source',
  'pskreporter',
  'clusterEnabled',
  'clusterHost',
  'clusterHosts',
  'aprsIsEnabled',
  'aprsIsHost',
  'aprsIsPort',
  'aprsIsRadiusKm',
  'aprsIsWatchCalls',
  'aprsIsWeather',
  'aprsIsObjects',
  'aprsIsMessages',
  'aprsIsUplink',
  'aprsStationTtlMin',
  'aprsChannelMhz',
  'aprsSymbolCode',
  'aprsSymbolTable',
  'aprsComment',
  'aprsPath',
  'aprsSsid',
  'audioIn',
  'audioOut',
  'voiceMicDevice',
  'txLevel',
  'rxGain',
  'monitorEnabled',
  'monitorDevice',
  'monitorLevel',
  'stationPowerW',
  'units',
  'maxPowerPhone',
  'maxPowerCw',
  'maxPowerDigital',
  'maxPowerAm',
  'propEngine',
  'saveWav',
  'lotwMaxAgeDays',
  'antTxGainDbi',
  'antRxGainDbi',
  'journeyStreakEnabled',
  'txWatchdogMin',
  'txEven',
  'rxOffsetHz',
  'txOffsetHz',
  'holdTxFreq',
  'clockCheck',
  'autoLog',
  'promptToLog',
  'saveQsoWav',
  'preferRrr',
  'cqMaxCalls',
  'cqPauseSecs',
  'directedMaxCalls',
  'chatMaxCycles',
  'chatImplicitAck',
  'cqStallOvers',
  'disableTxAfter73',
  'bandEdgeTones',
  'cwIdAfter73',
  'clearDxAfterLog',
  'doubleClickSetsTx',
  'tuneTimeoutSecs',
  'tunePowerPct',
  'splitMode',
  'decodeDepth',
  'decodeFLowHz',
  'decodeFHighHz',
  'apDecode',
  'apCqOnly',
  'singleDecode',
  'specialOp',
  'workingFrequencies',
  'qsyEnabled',
  'qsySet',
  'qsyCadence',
  'issSstvAutoArm',
  'sstvRxAutoArm',
  'sstvDefaultTxMode',
  'sstvTxPowerPct',
  'pskRxAutoArm',
  'rttyRxAutoArm',
  'alertMyCall',
  'alertCq',
  'alertNew',
  'potaNewActivationAlert',
  'logReportsToComments',
  'alertConfirmTier',
  'alertDxccBands',
  'alertGridBands',
  'b4MatchMode',
  'alertRareGridBands',
  'wheelTuneSensitivity',
  'announceVerbosity',
  'soundTxState',
  'soundDecodeTick',
  'bestCaller',
  'bestCallerMinSnr',
  'blockedCalls',
  'wantedCalls',
  'pounceThreshold',
  'lotwUseAdifLocation',
  'lotwAutoUpload',
  'lotwAutoUploadHours',
  'lotwLastAutoUploadUnix',
  'qrzLogbookUpload',
  'qrzAutoSync',
  'qrzSyncHours',
  'qrzLastSyncUnix',
  'clublogUpload',
  'eqslUpload',
  'hrdlogUpload',
  'wrlUpload',
  'n3fjpUpload',
  'cloudlogUpload',
  'openingRegional',
  'macros',
  'contestCategoryAssisted',
  'contestCategoryOperator',
  'contestCategoryPower',
  'contestCategoryStation',
  'contestCheck',
  'contestCqZone',
  'contestItuZone',
  'contestPower',
  'contestQthCounty',
  'contestQthState',
  'cwReverse',
] as const
export const WITHHELD_SETTINGS_KEYS = [
  'lotwUsername',
  'lotwLastQsl',
  'lotwStationLocation',
  'tqslPath',
  'eqslUsername',
  'eqslLastSync',
  'qrzUsername',
  'hamqthUsername',
  'clublogEmail',
  'clublogCallsign',
  'clublogApiKey',
  'eqslQthNickname',
  'wrlLogbookId',
  'cloudlogUrl',
  'cloudlogStationId',
  'cloudlogKey',
  'voiceMessages',
] as const
/** The per-radio withheld list, mirroring Rust RADIO_WITHHELD_KEYS. Empty today by design: it
 *  exists so the first per-radio credential has somewhere to go that is not the wire, and so the
 *  browser can refuse a document that carries one anyway. CI pins it to the Rust list. */
export const WITHHELD_RADIO_KEYS: string[] = []
export const SETTINGS_SHAPES = {
  "mycall": "string",
  "mygrid": "string",
  "opName": "string",
  "opState": "string",
  "catBrokerPtt": "boolean",
  "band": "string",
  "dialMhz": "number",
  "sideband": "string",
  "phoneMode": "string",
  "rptrShift": "string",
  "ctcssToneHz": "number",
  "q65PeriodS": "number",
  "beaconTxPercent": "number",
  "beaconPowerDbm": "number",
  "beaconRrSlot": "number",
  "beaconRrSlots": "number",
  "fst4PeriodS": "number",
  "msk144PeriodS": "number",
  "jt65Submode": "number",
  "q65Submode": "number",
  "js8Speed": "number",
  "js8RxSpeeds": "number",
  "js8HbIntervalMin": "number",
  "js8CqIntervalMin": "number",
  "js8HbAck": "boolean",
  "js8Autoreply": "boolean",
  "js8Relay": "boolean",
  "js8IdleWatchdogMin": "number",
  "js8Info": "string",
  "js8Status": "string",
  "js8Groups": "array",
  "rptrOffsetOverrideHz": "number",
  "fdActive": "boolean",
  "fdClass": "string",
  "fdEvent": "string",
  "fdPowerMult": "number",
  "fdBonuses": "array",
  "fdBonusesPlanned": "array",
  "n3fjpHost": "string",
  "n3fjpPort": "number",
  "n3fjpUseEnter": "boolean",
  "n3fjpReportBand": "boolean",
  "dxkeeperHost": "string",
  "dxkeeperBasePort": "number",
  "dxkeeperUploads": "boolean",
  "n1mmAddr": "string",
  "n1mmUpload": "boolean",
  "fdSection": "string",
  "fdOperator": "string",
  "fdHostEnable": "boolean",
  "fdHostPort": "number",
  "fdEventName": "string",
  "fdJoinAddr": "string",
  "fdPositionName": "string",
  "fdPositionId": "string",
  "fdScoreboard": "boolean",
  "fdScoreboardPort": "number",
  "connectWeb": "boolean",
  "connectWebPort": "number",
  "betaUpdates": "boolean",
  "beacon": "boolean",
  "harqEnabled": "boolean",
  "pttMethod": "string",
  "rigModel": "number",
  "rigModelName": "string",
  "serialPort": "string",
  "pttSerialPort": "string",
  "catRtsState": "string",
  "catDtrState": "string",
  "catRtsKeysPtt": "boolean",
  "catSerialHandshake": "string",
  "catPttLineState": "string",
  "baud": "number",
  "rigConn": "string",
  "rigAddr": "string",
  "omnirigSlot": "number",
  "icomNativeCat": "boolean",
  "splitDetectEnabled": "boolean",
  "yaesuRfScope": "boolean",
  "icomDataMode": "number",
  "dataModesPlainSsb": "boolean",
  "sstvHoldDataSubmode": "boolean",
  "setRigMode": "boolean",
  "operatingMode": "string",
  "licenseClass": "string",
  "cwKeyer": "string",
  "winkeyerPort": "string",
  "cwKeyPort": "string",
  "cwKeyLine": "string",
  "cwPitchHz": "number",
  "cwWpm": "number",
  "rttyBackend": "string",
  "rttyFskLine": "string",
  "rttyFskPort": "string",
  "rttyBaud": "number",
  "rttyShiftHz": "number",
  "rttyReverse": "boolean",
  "aiCwEnabled": "boolean",
  "unassistedMode": "boolean",
  "rigctldPort": "number",
  "rotatorModel": "number",
  "rotatorPort": "string",
  "rotatorBaud": "number",
  "ampModel": "string",
  "ampPort": "string",
  "ampFollowBand": "boolean",
  "rotatorHost": "string",
  "rotParkAz": "number",
  "rotParkEl": "number",
  "rotReadyAz": "number",
  "rotReadyEl": "number",
  "rotPostPass": "string",
  "rotTolAzDeg": "number",
  "rotTolElDeg": "number",
  "rotCalAzDeg": "number",
  "rotCalElDeg": "number",
  "rotAllowFlip": "boolean",
  "satDopplerOff": "boolean",
  "satVfoMap": "string",
  "satUplinkRadios": "nullable-array",
  "satMinShiftHz": "number",
  "satUpdateMs": "number",
  "satPassAlertSoundOff": "boolean",
  "catBroker": "boolean",
  "catBrokerPort": "number",
  "flexRadioIp": "string",
  "flexNativePan": "boolean",
  "flexNativeAudio": "boolean",
  "radios": "array",
  "activeRadio": "number",
  "radioPegged": "boolean",
  "simultaneousRadios": "boolean",
  "routingRules": "array",
  "defaultRadio": "nullable-number",
  "wsjtxUdp": "boolean",
  "wsjtxUdpAddr": "string",
  "writeAllTxt": "boolean",
  "diagDebugLog": "boolean",
  "hrdLogging": "boolean",
  "hrdUdpAddr": "string",
  "companionAddr": "string",
  "source": "string",
  "pskreporter": "boolean",
  "clusterEnabled": "boolean",
  "clusterHost": "string",
  "clusterHosts": "array",
  "aprsIsEnabled": "boolean",
  "aprsIsHost": "string",
  "aprsIsPort": "number",
  "aprsIsRadiusKm": "number",
  "aprsIsWatchCalls": "array",
  "aprsIsWeather": "boolean",
  "aprsIsObjects": "boolean",
  "aprsIsMessages": "boolean",
  "aprsIsUplink": "boolean",
  "aprsStationTtlMin": "number",
  "aprsChannelMhz": "nullable-number",
  "aprsSymbolCode": "string",
  "aprsSymbolTable": "string",
  "aprsComment": "string",
  "aprsPath": "array",
  "aprsSsid": "nullable-number",
  "audioIn": "string",
  "audioOut": "string",
  "voiceMicDevice": "string",
  "txLevel": "number",
  "rxGain": "number",
  "monitorEnabled": "boolean",
  "monitorDevice": "string",
  "monitorLevel": "number",
  "stationPowerW": "nullable-number",
  "units": "string",
  "maxPowerPhone": "nullable-number",
  "maxPowerCw": "nullable-number",
  "maxPowerDigital": "nullable-number",
  "maxPowerAm": "nullable-number",
  "propEngine": "string",
  "saveWav": "string",
  "lotwMaxAgeDays": "number",
  "antTxGainDbi": "number",
  "antRxGainDbi": "number",
  "journeyStreakEnabled": "boolean",
  "txWatchdogMin": "number",
  "txEven": "boolean",
  "rxOffsetHz": "number",
  "txOffsetHz": "number",
  "holdTxFreq": "boolean",
  "clockCheck": "boolean",
  "autoLog": "boolean",
  "promptToLog": "boolean",
  "saveQsoWav": "boolean",
  "preferRrr": "boolean",
  "cqMaxCalls": "nullable-number",
  "cqPauseSecs": "nullable-number",
  "directedMaxCalls": "nullable-number",
  "chatMaxCycles": "nullable-number",
  "chatImplicitAck": "boolean",
  "cqStallOvers": "nullable-number",
  "disableTxAfter73": "boolean",
  "bandEdgeTones": "boolean",
  "cwIdAfter73": "boolean",
  "clearDxAfterLog": "boolean",
  "doubleClickSetsTx": "boolean",
  "tuneTimeoutSecs": "number",
  "tunePowerPct": "nullable-number",
  "splitMode": "string",
  "decodeDepth": "number",
  "decodeFLowHz": "number",
  "decodeFHighHz": "number",
  "apDecode": "boolean",
  "apCqOnly": "boolean",
  "singleDecode": "boolean",
  "specialOp": "string",
  "workingFrequencies": "array",
  "qsyEnabled": "boolean",
  "qsySet": "array",
  "qsyCadence": "number",
  "issSstvAutoArm": "boolean",
  "sstvRxAutoArm": "boolean",
  "sstvDefaultTxMode": "string",
  "sstvTxPowerPct": "nullable-number",
  "pskRxAutoArm": "boolean",
  "rttyRxAutoArm": "boolean",
  "alertMyCall": "boolean",
  "alertCq": "boolean",
  "alertNew": "boolean",
  "potaNewActivationAlert": "boolean",
  "logReportsToComments": "boolean",
  "alertConfirmTier": "boolean",
  "alertDxccBands": "string",
  "alertGridBands": "string",
  "b4MatchMode": "boolean",
  "alertRareGridBands": "string",
  "wheelTuneSensitivity": "number",
  "announceVerbosity": "string",
  "soundTxState": "boolean",
  "soundDecodeTick": "boolean",
  "bestCaller": "string",
  "bestCallerMinSnr": "nullable-number",
  "blockedCalls": "array",
  "wantedCalls": "array",
  "pounceThreshold": "string",
  "lotwUseAdifLocation": "boolean",
  "lotwAutoUpload": "boolean",
  "lotwAutoUploadHours": "number",
  "lotwLastAutoUploadUnix": "number",
  "qrzLogbookUpload": "boolean",
  "qrzAutoSync": "boolean",
  "qrzSyncHours": "number",
  "qrzLastSyncUnix": "number",
  "clublogUpload": "boolean",
  "eqslUpload": "boolean",
  "hrdlogUpload": "boolean",
  "wrlUpload": "boolean",
  "n3fjpUpload": "boolean",
  "cloudlogUpload": "boolean",
  "openingRegional": "boolean",
  "macros": "object",
  "contestCategoryAssisted": "string",
  "contestCategoryOperator": "string",
  "contestCategoryPower": "string",
  "contestCategoryStation": "string",
  "contestCheck": "string",
  "contestCqZone": "number",
  "contestItuZone": "number",
  "contestPower": "string",
  "contestQthCounty": "string",
  "contestQthState": "string",
  "cwReverse": "boolean"
} as const
