// ---------------------------------------------------------------------------
// THE ILLINOIS QSO PARTY'S TWO EXCHANGE UNIVERSES — the `il_counties` and `il_mults`
// domains of the rules seed, mirrored so the entry strip can answer with NO IPC: the
// while-typing verdict, the county type-ahead ("Cook" → COOK) and the multiplier board
// all read these tables on every keystroke.
//
// ⚠️ A MIRROR, and a guarded one: tempo-core's
// `the_typescript_ilqp_mirror_matches_the_seed_domains` reads this file and fails on any
// code, name or order that differs from the seed. Change the seed and this together.
//
// The codes are INVARIANT TOKENS — the sponsor's own county abbreviations (one of which,
// LEE, is three letters where the other 101 are four) and the state/province codes its
// records table uses. The names are display text: they feed the type-ahead and a tooltip,
// and they are never sent on the air.
// ---------------------------------------------------------------------------

/** One legal exchange value: the code sent on the air and the place it names. */
export interface IlqpValue {
  code: string
  name: string
}

/** The 102 counties of the sponsor's own COUNTIES CHART, in its alphabetical order. */
export const ILQP_COUNTIES: IlqpValue[] = [
  { code: 'ADAM', name: 'Adams' },
  { code: 'ALEX', name: 'Alexander' },
  { code: 'BOND', name: 'Bond' },
  { code: 'BOON', name: 'Boone' },
  { code: 'BROW', name: 'Brown' },
  { code: 'BURO', name: 'Bureau' },
  { code: 'CALH', name: 'Calhoun' },
  { code: 'CARR', name: 'Carroll' },
  { code: 'CASS', name: 'Cass' },
  { code: 'CHAM', name: 'Champaign' },
  { code: 'CHRS', name: 'Christian' },
  { code: 'CLRK', name: 'Clark' },
  { code: 'CLAY', name: 'Clay' },
  { code: 'CLNT', name: 'Clinton' },
  { code: 'COLE', name: 'Coles' },
  { code: 'COOK', name: 'Cook' },
  { code: 'CRAW', name: 'Crawford' },
  { code: 'CUMB', name: 'Cumberland' },
  { code: 'DEKA', name: 'DeKalb' },
  { code: 'DEWT', name: 'DeWitt' },
  { code: 'DOUG', name: 'Douglas' },
  { code: 'DUPG', name: 'DuPage' },
  { code: 'EDGR', name: 'Edgar' },
  { code: 'EDWA', name: 'Edwards' },
  { code: 'EFFG', name: 'Effingham' },
  { code: 'FAYE', name: 'Fayette' },
  { code: 'FORD', name: 'Ford' },
  { code: 'FRNK', name: 'Franklin' },
  { code: 'FULT', name: 'Fulton' },
  { code: 'GALL', name: 'Gallatin' },
  { code: 'GREE', name: 'Greene' },
  { code: 'GRUN', name: 'Grundy' },
  { code: 'HAML', name: 'Hamilton' },
  { code: 'HANC', name: 'Hancock' },
  { code: 'HARD', name: 'Hardin' },
  { code: 'HNDR', name: 'Henderson' },
  { code: 'HENR', name: 'Henry' },
  { code: 'IROQ', name: 'Iroquois' },
  { code: 'JACK', name: 'Jackson' },
  { code: 'JASP', name: 'Jasper' },
  { code: 'JEFF', name: 'Jefferson' },
  { code: 'JERS', name: 'Jersey' },
  { code: 'JODA', name: 'JoDaviess' },
  { code: 'JOHN', name: 'Johnson' },
  { code: 'KANE', name: 'Kane' },
  { code: 'KANK', name: 'Kankakee' },
  { code: 'KEND', name: 'Kendall' },
  { code: 'KNOX', name: 'Knox' },
  { code: 'LAKE', name: 'Lake' },
  { code: 'LASA', name: 'LaSalle' },
  { code: 'LAWR', name: 'Lawrence' },
  { code: 'LEE', name: 'Lee' },
  { code: 'LIVG', name: 'Livingston' },
  { code: 'LOGN', name: 'Logan' },
  { code: 'MACN', name: 'Macon' },
  { code: 'MCPN', name: 'Macoupin' },
  { code: 'MADN', name: 'Madison' },
  { code: 'MARI', name: 'Marion' },
  { code: 'MSHL', name: 'Marshall' },
  { code: 'MASN', name: 'Mason' },
  { code: 'MSSC', name: 'Massac' },
  { code: 'MCDN', name: 'McDonough' },
  { code: 'MCHE', name: 'McHenry' },
  { code: 'MCLN', name: 'McLean' },
  { code: 'MNRD', name: 'Menard' },
  { code: 'MRCR', name: 'Mercer' },
  { code: 'MNRO', name: 'Monroe' },
  { code: 'MNTG', name: 'Montgomery' },
  { code: 'MORG', name: 'Morgan' },
  { code: 'MOUL', name: 'Moultrie' },
  { code: 'OGLE', name: 'Ogle' },
  { code: 'PEOR', name: 'Peoria' },
  { code: 'PERR', name: 'Perry' },
  { code: 'PIAT', name: 'Piatt' },
  { code: 'PIKE', name: 'Pike' },
  { code: 'POPE', name: 'Pope' },
  { code: 'PULA', name: 'Pulaski' },
  { code: 'PUTN', name: 'Putnam' },
  { code: 'RAND', name: 'Randolph' },
  { code: 'RICH', name: 'Richland' },
  { code: 'ROCK', name: 'Rock Island' },
  { code: 'SALI', name: 'Saline' },
  { code: 'SANG', name: 'Sangamon' },
  { code: 'SCHY', name: 'Schuyler' },
  { code: 'SCOT', name: 'Scott' },
  { code: 'SHEL', name: 'Shelby' },
  { code: 'STAR', name: 'Stark' },
  { code: 'SCLA', name: 'St. Clair' },
  { code: 'STEP', name: 'Stephenson' },
  { code: 'TAZW', name: 'Tazewell' },
  { code: 'UNIO', name: 'Union' },
  { code: 'VERM', name: 'Vermilion' },
  { code: 'WABA', name: 'Wabash' },
  { code: 'WARR', name: 'Warren' },
  { code: 'WASH', name: 'Washington' },
  { code: 'WAYN', name: 'Wayne' },
  { code: 'WHIT', name: 'White' },
  { code: 'WTSD', name: 'Whiteside' },
  { code: 'WILL', name: 'Will' },
  { code: 'WMSN', name: 'Williamson' },
  { code: 'WBGO', name: 'Winnebago' },
  { code: 'WOOD', name: 'Woodford' },
]

/** What a station outside Illinois sends: 49 US states and DC (Illinois itself cannot be
 *  one), then the Canadian codes — the sponsor's own NF/LAB/PEI spellings beside the
 *  modern NL/PE, since it publishes no exchange code list and a VE station may send
 *  either. */
export const ILQP_MULTS: IlqpValue[] = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DC', name: 'District of Columbia' },
  { code: 'DE', name: 'Delaware' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
  { code: 'NL', name: 'Newfoundland and Labrador' },
  { code: 'NF', name: 'Newfoundland' },
  { code: 'LAB', name: 'Labrador' },
  { code: 'PE', name: 'Prince Edward Island' },
  { code: 'PEI', name: 'Prince Edward Island' },
  { code: 'NS', name: 'Nova Scotia' },
  { code: 'NB', name: 'New Brunswick' },
  { code: 'QC', name: 'Quebec' },
  { code: 'ON', name: 'Ontario' },
  { code: 'MB', name: 'Manitoba' },
  { code: 'SK', name: 'Saskatchewan' },
  { code: 'AB', name: 'Alberta' },
  { code: 'BC', name: 'British Columbia' },
  { code: 'NT', name: 'Northwest Territories' },
  { code: 'NU', name: 'Nunavut' },
  { code: 'YT', name: 'Yukon' },
]
