#!/usr/bin/env bash
# Mirror the current GitHub `main` tree to the SourceForge git repo.
#
#   ./scripts/mirror-to-sourceforge.sh            # mirror HEAD
#   ./scripts/mirror-to-sourceforge.sh --dry-run  # show what would be pushed
#
# GitHub is primary. This repo IS the published source — nothing is stripped, so the
# mirror is a plain tree copy with no scrub, no graft, no hand-merge.
#
# WHY A TREE COPY AND NOT A HISTORY PUSH
# SourceForge rejects non-fast-forward pushes even with --force ("remote rejected …
# non-fast-forward" — verified 2026-07-20), so SF's history cannot be replaced with
# GitHub's without a branch-swap through their admin web UI. SF's main is a 36-commit
# snapshot lineage rather than a real history anyway, so this script keeps that shape:
# each run adds ONE fast-forward commit carrying the exact GitHub tree. That satisfies
# GPL source availability (the complete tree is present and matches the binaries) with
# no manual step and no second history to reason about.
#
# The failure this exists to prevent: before 2026-07-20 each fix had to be committed
# TWICE by hand, once per remote, on two different parents. A stale hand-merge in that
# process shipped source that could not compile for two releases.
set -euo pipefail

bold() { printf '\n\033[1m%s\033[0m\n' "$*"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
die()  { printf '\n\033[31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"

DRY=0
for a in "$@"; do
  case "$a" in
    --dry-run) DRY=1 ;;
    -h|--help) sed -n '2,8p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) die "unknown option: $a" ;;
  esac
done

# SF needs this key explicitly, or it fails "Too many authentication failures" as ssh
# offers other identities first. A FAILED fetch leaves a stale ref that looks exactly
# like a current one, so this is not optional politeness.
export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/hamradiotools_ed25519 -o IdentitiesOnly=yes"

bold "1/4  Preflight"
[ -z "$(git status --porcelain)" ] || die "working tree is dirty — commit or stash first"
git remote get-url sf >/dev/null 2>&1 || die "no 'sf' remote configured"
git fetch -q origin || die "git fetch origin FAILED — refusing to mirror from a stale ref"
git fetch -q sf     || die "git fetch sf FAILED — refusing to push onto a stale ref"
HEAD_SHA="$(git rev-parse HEAD)"
[ "$HEAD_SHA" = "$(git rev-parse origin/main)" ] || \
  die "HEAD is not origin/main — push to GitHub first; it is the primary."
ok "clean tree, remotes fresh, HEAD == origin/main ($(git rev-parse --short HEAD))"

bold "2/4  Stage SF worktree"
WT="$(mktemp -d)"; trap 'rm -rf "$WT"' EXIT
git worktree add -q --detach "$WT/sf" sf/main
ok "sf/main at $(git -C "$WT/sf" rev-parse --short HEAD)"

# Copy the tracked GitHub tree over the SF checkout, then stage everything so files
# deleted upstream are deleted here too. `git archive` emits ONLY tracked files, so
# gitignored local state (tasks/, the DeepCW model, build outputs) can never leak in.
find "${WT:?}/sf" -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +
git archive "$HEAD_SHA" | tar -x -C "$WT/sf"
git -C "$WT/sf" add -A

bold "3/4  Gates"
# The tree that lands on SF must equal the GitHub tree exactly — that equality is the
# entire guarantee this script offers.
STAGED_TREE="$(git -C "$WT/sf" write-tree)"
[ "$STAGED_TREE" = "$(git rev-parse "$HEAD_SHA^{tree}")" ] || \
  die "staged SF tree != GitHub tree — refusing to push"
ok "tree matches GitHub exactly"
git -C "$WT/sf" diff --cached --name-only | grep -q '^tasks/' && die "tasks/ staged — ABORT"
git -C "$WT/sf" grep --cached -l 'srmccall' >/dev/null 2>&1 && die "home path in tree — ABORT"
ok "no internal notes, no home paths"

if git -C "$WT/sf" diff --cached --quiet; then
  ok "SF already matches GitHub — nothing to do"; exit 0
fi

bold "4/4  Push"
if [ "$DRY" = 1 ]; then
  git -C "$WT/sf" diff --cached --stat | tail -20
  printf '\n  (--dry-run: nothing pushed)\n'
  exit 0
fi
git -C "$WT/sf" commit -q -m "Mirror GitHub main @ $(git rev-parse --short "$HEAD_SHA")

Tree-for-tree copy of https://github.com/kd9taw/Nexus at $HEAD_SHA.
GitHub is primary; this repo mirrors it. Generated by scripts/mirror-to-sourceforge.sh."
git -C "$WT/sf" push sf HEAD:main
ok "pushed — SF now carries the GitHub tree at $(git rev-parse --short "$HEAD_SHA")"
git worktree remove --force "$WT/sf" 2>/dev/null || true
