//! Grid-square → US-state lookup for the WAS "New State" need hint.
//!
//! A best-guess US state for a 4-char Maidenhead grid, from a table generated by
//! `scripts/gen-grid-state.mjs` (us-atlas state polygons → the dominant state
//! among sample points in each cell). This is a HINT: a heard station's 4-char
//! grid (own decode / PSK Reporter) resolves to a probable state for free — no
//! per-call lookup. It is coarse on state borders (a 2°×1° cell can straddle
//! two states; the dominant one wins), so it drives the *board* only. The actual
//! WAS award credit still comes from the confirmed QSO's logged ADIF `STATE`.
//!
//! Packing matches `grid_rarity.bin`: `index = lonIdx*180 + latIdx`, one byte
//! per cell; byte 0 = not a WAS state, 1..=50 = `awards::WAS_STATES[byte-1]`.

/// One byte per 4-char grid cell (32,400 cells). See the module docs for packing.
static TABLE: &[u8; 32_400] = include_bytes!("../data/grid_state.bin");

/// Best-guess US state (2-letter WAS code) for a grid (length ≥ 4 — the
/// field+square is all that matters). `None` for a non-US grid or an invalid
/// Maidenhead string. The returned code is always one of the 50 WAS states.
pub fn state_for_grid(grid: &str) -> Option<&'static str> {
    let idx = grid_index(grid)? as usize;
    let code = TABLE[idx];
    if code == 0 {
        return None;
    }
    crate::awards::WAS_STATES.get((code - 1) as usize).copied()
}

/// Parse a Maidenhead grid to its field+square cell index. Identical to
/// `gridrarity::grid_index` — the two tables share the same packing.
fn grid_index(grid: &str) -> Option<u16> {
    let b = grid.trim().as_bytes();
    if b.len() < 4 {
        return None;
    }
    let f1 = b[0].to_ascii_uppercase();
    let f2 = b[1].to_ascii_uppercase();
    let (d1, d2) = (b[2], b[3]);
    if !(b'A'..=b'R').contains(&f1)
        || !(b'A'..=b'R').contains(&f2)
        || !d1.is_ascii_digit()
        || !d2.is_ascii_digit()
    {
        return None;
    }
    let lon_idx = (f1 - b'A') as u16 * 10 + (d1 - b'0') as u16;
    let lat_idx = (f2 - b'A') as u16 * 10 + (d2 - b'0') as u16;
    Some(lon_idx * 180 + lat_idx)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn resolves_us_grids_to_their_state() {
        // The generator's sanity anchors, verified from the Rust side.
        assert_eq!(state_for_grid("EN52"), Some("WI")); // Milwaukee
        assert_eq!(state_for_grid("FN31"), Some("CT")); // Connecticut
        assert_eq!(state_for_grid("EM12"), Some("TX")); // Dallas
        assert_eq!(state_for_grid("DM79"), Some("CO")); // Denver
        assert_eq!(state_for_grid("CN87"), Some("WA")); // Seattle
        assert_eq!(state_for_grid("BP51"), Some("AK")); // Anchorage
        assert_eq!(state_for_grid("BL11"), Some("HI")); // Honolulu (small-island)
    }

    #[test]
    fn non_us_and_invalid_grids_resolve_to_none() {
        assert_eq!(state_for_grid("IO91"), None); // London
        assert_eq!(state_for_grid("JN58"), None); // Munich
        assert_eq!(state_for_grid(""), None);
        assert_eq!(state_for_grid("XX"), None); // too short
        assert_eq!(state_for_grid("ZZ99"), None); // out of range
    }

    #[test]
    fn delaware_and_rhode_island_resolve_to_none_not_a_wrong_neighbor() {
        // DE/RI are smaller than a 4-char grid cell, so the table leaves their
        // cells 0 rather than emit a confident wrong neighbor (NJ/MA). A precise
        // state for those comes from a callsign lookup, not the grid.
        assert_eq!(state_for_grid("FM29"), None); // Delaware
        assert_eq!(state_for_grid("FN41"), None); // Rhode Island
    }

    #[test]
    fn accepts_longer_grids_by_truncating_to_field_square() {
        assert_eq!(state_for_grid("EN52wa"), Some("WI"));
    }

    #[test]
    fn every_table_code_is_a_valid_was_state() {
        for &code in TABLE.iter() {
            if code != 0 {
                assert!(
                    crate::awards::WAS_STATES.get((code - 1) as usize).is_some(),
                    "table byte {code} out of WAS_STATES range"
                );
            }
        }
    }
}
